<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="WireMock.Net" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\PicPay.Api\PicPay.Api.csproj" />
  </ItemGroup>
</Project>
